travis:
  secure:
    BINSTAR_TOKEN: uKqeWlFmLeGEAvQ0KUaq6LZhVwg6uxV0jTdelNenQeee/jUHuRgG1danG/9vbyCfGuOTPOiRY6yiRvnAaOVr58+TDC5TfeAZhoYARDzPv4vVllm4pYuEaUdOS7XOqPLTR40sshbkz/jrDuRG+Sa6F++YCF9mZfGx1Po/QED6BZFluqArIrKyYm04V+txJFh1gABcXkdulHXV2g/QWBv6QEbFcHC6ZsfPacFoLx0dcWvZWa8OS/lBRBBKMdF3Nvux0ZNxIaHjMtx9dvwlmTsJSPaP8lLs5RHtDMWraA+tFf80DE2bDsq6r+3v8F5Dh9Dx0RnjdTBewAdonh7kZHk+uXqJwRlW2ilitBCDjpmkBSVYoMJgcgJf9QIbyY6pAE2623PjLhLVqc/Y5BnhavmrIX2tzFPRJGT2V6J/1FHcbUawmw48RMHEVBE6Ti9Dk7faUZq15An+Xv2ulOBzEKYPSGT0sFlrtpYmpivhO6qZvpziJSD3I01bOlj7PmMjuZe8vBB3xdqFskyXi3aZPmSz0BBItVpsM449m0HlmVoivKHXNylexbd9HgT+G8S5kxosCZWNYMah03kiPpOkDO4NtwRo1opH3b3iRMgxM6ISgdYbM2+Mx4xLbdoSySCYRvJdcc9QagoHVyVaYwT+EkK013/uGevY8eUSWKnQyvB0ef8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
