travis:
  secure:
    BINSTAR_TOKEN: u5jmswKkfMbxkJLV+uSobnLnXEJEj39kjPOpgqxfWWjIvtGz0927v4AcDGL/uPNpLR9az4uNWDhNZBCgzWS5qF+ZTHc6UEXkTT7BbRVZheP2/Oir5SthxmcGH1mJ27z1GBdzFwBE/ebEEGnRU7TPJSJs62wRY9q2SfMgW/ftZMcPPASAwlJrpILAz+pw7tPNI536BimjEuUtatBtQLVULeaar6heNUQWeT0uEk0goMQuaB+jb0QinZ3ENLf3yEnWJnLk5fTRchsdKeWRLrP+mG+tmHcFkUOOmEIW7sDfTNCH0mTcnlXo9/zeQwpW2BrIiK+Z66D6VnydkrbOppSP2dSsJFXCABawyfWnPAfx6GRNA/r/woO+z66mJL1CJBOzLdpcVZtm7F2UVaJ7H/p+5sxq7nmnnx9jhnECp8/Kh+At5vLkNRZX/SZ1SsqoXN2hNgc4BWoz33rb6ZzrSKgqtwlu3hvy+nQzmRp0+cu3LXS6Zb4vpahDOVjOZZTuKrPTgm+0TqaYgrBq3/o8UXgZVVsNaaselqXu4XSd5tq39qs7lzcSPbIdLt1UMzgV/bPYqY7WQzbqZjcKDPZctSw4Zr7HmSv5YMAPHtwjHahlKSUjhGeSxW5I0n2cgpfqFn/LHQVP9vwYqdOhBpr41h77X5KAMglRsjXE5hdM50GQEc8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
